In [1]:
import pandas as pd
import unicodedata
from rapidfuzz import process, fuzz

df = pd.read_csv("~/Desktop/Football_Stats/xG/final_player_stats.csv")

NORMALIZE NAMES

In [2]:
def normalize_name(name):
    name = str(name).lower().strip()
    name = unicodedata.normalize("NFKD", name)
    name = name.encode("ascii", "ignore").decode("utf-8")
    name = name.replace(".", "")
    name = name.replace("-", " ")
    name = " ".join(name.split())
    return name

FIFA RATNGS TABLE

In [3]:
cols = ["Player Name","Att. Position", "Finishing", "Shot Power", "Long Shots", "Volleys", "Penalties", 'GK Positioning', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Reflexes']
df = df[cols].copy()
df.head()

,Player Name,Att. Position,Finishing,Shot Power,Long Shots,Volleys,Penalties,GK Positioning,GK Diving,GK Handling,GK Kicking,GK Reflexes
0,Adam Smith,65.0,52.0,72.0,68.0,43.0,55.0,9.0,8.0,9.0,15.0,6.0
1,Antoine Semenyo,68.0,68.0,77.0,64.0,56.0,51.0,15.0,10.0,11.0,14.0,7.0
2,Chris Mepham,39.0,32.0,52.0,32.0,33.0,44.0,14.0,10.0,10.0,12.0,12.0
3,Dango Ouattara,74.0,72.0,64.0,66.0,49.0,66.0,14.0,9.0,6.0,13.0,10.0
4,Darren Randolph,11.0,14.0,50.0,14.0,16.0,30.0,70.0,74.0,70.0,66.0,73.0

In [4]:
df["Shooting"] = (df["Att. Position"] + df["Finishing"] + df["Shot Power"] + df["Long Shots"] + df["Volleys"] + df["Penalties"]) / 6
df["Saving"] = (df["GK Diving"] + df["GK Handling"] + df["GK Positioning"] + df["GK Reflexes"])/4 
# I am not including "GK Kicking" since it doesn't give a measure of saving ability

# df.drop(["Att. Position", "Finishing", "Shot Power", "Long Shots", "Volleys", "Penalties",'GK Positioning', 'GK Diving', 'GK Handling',
#        'GK Kicking', 'GK Reflexes' ], axis=1, inplace=True)

df = df[["Player Name", "Shooting", "Saving"]].copy()

df["Source"] = "yarknyorulmaz/fifa-index-player-ratings-dataset-epl-v16-v24"
df.head()

,Player Name,Shooting,Saving,Source
0,Adam Smith,59.166667,8.00,yarknyorulmaz/fifa-index-player-ratings-datase...
1,Antoine Semenyo,64.000000,10.75,yarknyorulmaz/fifa-index-player-ratings-datase...
2,Chris Mepham,38.666667,11.50,yarknyorulmaz/fifa-index-player-ratings-datase...
3,Dango Ouattara,65.166667,9.75,yarknyorulmaz/fifa-index-player-ratings-datase...
4,Darren Randolph,22.500000,71.75,yarknyorulmaz/fifa-index-player-ratings-datase...

SUPPLIMENTAL PLAYERS

In [5]:
supplemental_players = pd.DataFrame([
    {
        "Player Name": "Adam Johnson",
        "statsbomb_name": "Adam Johnson",
        "Shooting": 73, 
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Steven Fletcher",
        "statsbomb_name": "Steven Fletcher",
        "Shooting": 73,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Mikel Arteta Amatriain",
        "statsbomb_name": "Mikel Arteta Amatriain",
        "Shooting": 75,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Ramires Santos do Nascimen.",
        "statsbomb_name": "Ramires Santos do Nascimento",
        "Shooting": 70,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Mauro Zárate",
        "statsbomb_name": "Mauro Matías Zárate",
        "Shooting": 78,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Éder Macedo Lopes",
        "statsbomb_name": "Éderzito António Macedo Lopes",
        "Shooting": 75,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Bradley Johnson",
        "statsbomb_name": "Bradley Johnson",
        "Shooting": 75,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Florian Thauvin",
        "statsbomb_name": "Florian Thauvin",
        "Shooting": 69,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Nikica Jelavić",
        "statsbomb_name": "Nikica Jelavić",
        "Shooting": 74,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Brede Hangeland",
        "statsbomb_name": "Brede Hangeland",
        "Shooting": 40,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Javier Hernández",
        "statsbomb_name": "Javier Hernández Balcázar",
        "Shooting": 80,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Miguel Layún",
        "statsbomb_name": "Miguel Arturo Layún Prado",
        "Shooting": 74,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Gary Hooper",
        "statsbomb_name": "Gary Hooper",
        "Shooting": 73,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Modibo Maïga",
        "statsbomb_name": "Modibo Maïga",
        "Shooting": 64,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Juan Cuadrado",
        "statsbomb_name": "Juan Guillermo Cuadrado Bello",
        "Shooting": 75,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Alessandro Diamanti",
        "statsbomb_name": "Alessandro Diamanti",
        "Shooting": 73,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Steven Taylor",
        "statsbomb_name": "Steven Taylor",
        "Shooting": 37,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
    {
        "Player Name": "Mathieu Debuchy",
        "statsbomb_name": "Mathieu Debuchy",
        "Shooting": 67,
        "Saving": 0,
        "Source": "manual_fifa_index"
    },
])

# "source": "manual_fifa_index"
# "rating_version": "FIFA 16"
# "notes": "Transferred out / absent from EPL snapshot"

In [6]:
df_extended = pd.concat(
    [df, supplemental_players[["Player Name", "Shooting", "Saving", "Source"]]],
    ignore_index=True
)

df_extended["fifa_name_norm"] = df_extended["Player Name"].apply(normalize_name)

STATSBOMB PLAYER TABLE

In [7]:
shots = pd.read_csv("~/Desktop/Football_Stats/xG/shots.csv")

sb_players = shots[["player_id", "player"]].drop_duplicates().copy()
sb_players["statsbomb_name_norm"] = sb_players["player"].apply(normalize_name)

FIFA PLAYER TABLE

In [8]:
fifa_players = df_extended[[
    "Player Name",
    "fifa_name_norm",
    "Shooting",
    "Saving",
    "Source"
]].drop_duplicates().copy()

EXACT MATCHES

In [9]:
exact_matches = sb_players.merge(
    fifa_players,
    left_on="statsbomb_name_norm",
    right_on="fifa_name_norm",
    how="inner"
)

exact_matches["match_method"] = "exact"
exact_matches["match_score"] = 100

In [10]:
matched_ids = set(exact_matches["player_id"])

unmatched_sb = sb_players[
    ~sb_players["player_id"].isin(matched_ids)
].copy()

print("Unmatched players:", len(unmatched_sb))
unmatched_sb

Unmatched players: 144

      player_id                       player          statsbomb_name_norm
4        3671.0          José Leonardo Ulloa          jose leonardo ulloa
16       3961.0                N''Golo Kanté                n''golo kante
31       4429.0          Yann Gérard M''Vila          yann gerard m''vila
34      43627.0    Jordi Gómez García-Penche    jordi gomez garcia penche
36       4041.0  José Salomón Rondón Giménez  jose salomon rondon gimenez
...         ...                          ...                          ...
7844    22058.0        Connor Steven Randall        connor steven randall
8036     3440.0         Tammy Bakumo-Abraham         tammy bakumo abraham
8347    13448.0          Bradley Shaun Smith          bradley shaun smith
8839    42900.0           Cheik Ismaël Tioté           cheik ismael tiote
8915    45014.0        Tokelo Anthony Rantie        tokelo anthony rantie

[144 rows x 3 columns]

In [11]:
fifa_name_list = fifa_players["fifa_name_norm"].tolist()

candidate_rows = []

for _, row in unmatched_sb.iterrows():
    candidates = process.extract(
        row["statsbomb_name_norm"],
        fifa_name_list,
        scorer=fuzz.WRatio,
        limit=5
    )

    for candidate_name, score, idx in candidates:
        fifa_row = fifa_players.iloc[idx]

        candidate_rows.append({
            "player_id": row["player_id"],
            "statsbomb_name": row["player"],
            "statsbomb_name_norm": row["statsbomb_name_norm"],
            "fifa_player_name": fifa_row["Player Name"],
            "fifa_name_norm": fifa_row["fifa_name_norm"],
            "Source": fifa_row["Source"],
            "match_score": score
        })

fuzzy_candidates = pd.DataFrame(candidate_rows)

fuzzy_candidates.sort_values(
    ["statsbomb_name", "match_score"],
    ascending=[True, False]
).head(100)

,player_id,statsbomb_name,statsbomb_name_norm,fifa_player_name,fifa_name_norm,Source,match_score
190,4090.0,Adam David Lallana,adam david lallana,Allan,allan,yarknyorulmaz/fifa-index-player-ratings-datase...,90.000000
191,4090.0,Adam David Lallana,adam david lallana,Allan,allan,yarknyorulmaz/fifa-index-player-ratings-datase...,90.000000
192,4090.0,Adam David Lallana,adam david lallana,Allan,allan,yarknyorulmaz/fifa-index-player-ratings-datase...,90.000000
193,4090.0,Adam David Lallana,adam david lallana,Allan,allan,yarknyorulmaz/fifa-index-player-ratings-datase...,90.000000
194,4090.0,Adam David Lallana,adam david lallana,Adam Smith,adam smith,yarknyorulmaz/fifa-index-player-ratings-datase...,85.500000
...,...,...,...,...,...,...,...
425,3044.0,Chancel Mbemba Mangulu,chancel mbemba mangulu,Chancel Mbemba,chancel mbemba,yarknyorulmaz/fifa-index-player-ratings-datase...,90.000000
426,3044.0,Chancel Mbemba Mangulu,chancel mbemba mangulu,Chancel Mbemba,chancel mbemba,yarknyorulmaz/fifa-index-player-ratings-datase...,90.000000
427,3044.0,Chancel Mbemba Mangulu,chancel mbemba mangulu,Àngel Rangel,angel rangel,yarknyorulmaz/fifa-index-player-ratings-datase...,64.125000
428,3044.0,Chancel Mbemba Mangulu,chancel mbemba mangulu,João Cancelo,joao cancelo,yarknyorulmaz/fifa-index-player-ratings-datase...,62.181818
429,3044.0,Chancel Mbemba Mangulu,chancel mbemba mangulu,João Cancelo,joao cancelo,yarknyorulmaz/fifa-index-player-ratings-datase...,62.181818

In [12]:
manual_overrides = {
    # "statsbomb normalized name": "fifa normalized name"
    # "mikel arteta amatriain": "mikel arteta amatriain", # **
    "fernando luiz rosa": "fernandinho",
    "jose leonardo ulloa": "leonardo ulloa",
    "n''golo kante": "n'golo kante",
    "yann gerard m''vila": "yann m'vila",
    "jordi gomez garcia penche": "jordi gomez",
    "jose salomon rondon gimenez": "salomon rondon",
    "claudio ariel yacob": "claudio yacob",
    "idrissa gana gueye": "idrissa gueye",
    "siem stefan de jong": "siem de jong",
    "carlos alberto sanchez moreno": "carlos sanchez",
    "ayoze perez gutierrez": "ayoze perez",
    "el hadji baye oumar niasse": "oumar niasse",
    "pape n''diaye souare": "pape souare",
    "odion jude ighalo": "odion ighalo",
    "chung yong lee": "lee chung yong",
    "gabriel armando de abreu": "gabriel",
    "alexis alejandro sanchez sanchez": "alexis sanchez",
    "hector bellerin moruno": "hector bellerin",
    "mohamed naser elsayed elneny": "mohamed elneny",
    "santiago cazorla gonzalez": "santi cazorla",
    "oluwaseyi babajide ojo": "sheyi ojo",
    "christian benteke liolo": "christian benteke",
    "christian dannemann eriksen": "christian eriksen",
    "bamidele alli": "dele alli",
    "sergio leonel aguero del castillo": "sergio aguero",
    "nicolas hernan otamendi": "nicolas otamendi",
    "gnegneri yaya toure": "yaya toure",
    "fernando luiz rosa": "fernandinho",
    "wilfried guemiand bony": "wilfried bony",
    "yannick bolasie yala": "yannick bolasie",
    "romelu lukaku menama": "romelu lukaku",
    "pedro eliezer rodriguez ledesma": "pedro",
    "mario suarez mata": "mario suarez",
    "daniel william john ings": "danny ings",
    "jack frank porteous cork": "jack cork",
}

sb_normalized = ["jose ramiro funes mori", "alexander banor tettey", "robert brady", "dame n''doye", "gary o''neil", "daniel andre sturridge", 
                 "roberto firmino barbosa de oliveira", "philippe coutinho correia", "adam david lallana", "bertrand isidore traore", 
                 "willian borges da silva", "francesc fabregas i soler", "kolo habib toure", "nathaniel edwin clyne", "james philip milner",
                 "jordan brian henderson", "bojan krkic perez", "ander herrera aguera", "marouane fellaini bakkioui", "juan manuel mata garcia", 
                 "juan carlos paredes reasco", "diego da silva costa", "oscar dos santos emboaba junior", "mame biram diouf", "guillermo varela olivera", 
                 "angelo obinze ogbonna", "alberto moreno perez", "divock okoth origi", "eunan o''kane", "sebastian coates nion", "andre ayew pele", 
                 "sung yeung ki", "gylfi or sigursson", "oriol romeu vidal", "jonathan howson", "ignacio monreal eraso", 
                 "joel nathaniel campbell samuels", "faustino marcos alberto rojo", "jesus navas gonzalez", "wayne mark rooney", "kurt happy zouma",
                 "cristian gamboa luna", "john o''shea", "mousa sidi yaya dembele", "jose miguel da rocha fonte", "radamel falcao garcia zarate",
                 "francis joseph coquelin", "gabriel imuetinyan agbonlahor", "max alain gradel", "jose manuel jurado marin", "chancel mbemba mangulu",
                 "dieumerci mbokani bezua", "sebastien aymar bassong nguena", "robert kenedy nunes do nascimento", "jonathan grant evans", 
                 "carles gil de pareja vicent", "brendan joel zibusiso galloway", "gerard deulofeu lazaro", "jose luis sanmartin mato", 
                 "clinton mua n''jie", "jefferson antonio montero vite", "fernando francisco reges", "david josue jimenez silva", 
                 "kelechi promise iheanacho", "andrew philip king", "lucas pezzini leiva", "cedric ricardo alves soares", "gabriel antoine obertan",
                 "adama traore diarra", "juan miguel jimenez lopez", "alexandre dimitri song billong", "luis antonio valencia mosquera", 
                 "victor chinedu anichebe", "marcin ryszard wasilewski", "pablo javier zabaleta girod", "martin gaston demichelis",
                 "gaston exequiel ramirez pereyra", "pedro mba obiang avomo", "yann kermorgant", "miguel angel britos cabrera", "angel rangel zaragoza",
                 "cesar azpilicueta tanco", "john michael nchekwube obinna", "rhu endly martina", "youssouf chafiq mulumbu ngangu",
                 "steven caulker", "sandro ranieri guimaraes cordeiro", "leroy fer", "daniel nii tackie mensah welbeck", "marc muniesa martinez",
                 "gilbert gianelli imbula wanga", "kevin linford stewart", "seydou doumbia", "jordi amat maas", "juan manuel iturbe arevalo", 
                 "osazemwinde peter odemwingie", "alexandre rodrigues da silva", "timothy evans fosu mensah", "emmanuel emenike", "connor steven randall",
                 "tammy bakumo abraham", "bradley shaun smith", "cheik ismael tiote", "tokelo anthony rantie", "matt grimes", "jose leonardo ulloa", 
                 "n''golo kante", "yann gerard m''vila", "jordi gomez garcia penche", "jose salomon rondon gimenez", "claudio ariel yacob", 
                 "idrissa gana gueye", "siem stefan de jong", "carlos alberto sanchez moreno", "ayoze perez gutierrez", "el hadji baye oumar niasse", 
                 "pape n''diaye souare", "odion jude ighalo", "chung yong lee", "gabriel armando de abreu", "alexis alejandro sanchez sanchez",
                 "hector bellerin moruno", "mohamed naser elsayed elneny", "santiago cazorla gonzalez", "oluwaseyi babajide ojo",  
                 "christian benteke liolo", "christian dannemann eriksen", "bamidele alli", "sergio leonel aguero del castillo", 
                 "nicolas hernan otamendi", "gnegneri yaya toure", "wilfried guemiand bony", "yannick bolasie yala", "romelu lukaku menama", 
                 "guangtai jiang", "enner remberto valencia lastra"]

fifa_normalized = [ "ramiro funes mori", "alexander tettey", "robbie brady", "dame n'doye", "gary o'neil", "daniel sturridge", "roberto firmino", 
                    "coutinho", "adam lallana", "bertrand traore", "willian", "cesc fabregas", "kolo toure", "nathaniel clyne", "james milner", 
                    "jordan henderson", "bojan", "ander herrera", "marouane fellaini", "juan mata", "juan carlos paredes", "diego costa", "oscar",
                    "mame diouf", "guillermo varela", "angelo ogbonna", "alberto moreno", "divock origi", "eunan o'kane", "sebastian coates", 
                    "andre ayew", "ki sung yueng", "gylfi sigursson", "oriol romeu", "jonny howson", "nacho monreal", "joel campbell", "marcos rojo", 
                    "jesus navas", "wayne rooney", "kurt zouma", "cristian gamboa", "john o'shea", "moussa dembele", "jose fonte", "falcao", 
                    "francis coquelin", "gabriel agbonlahor", "max gradel", "jurado", "chancel mbemba", "dieumerci mbokani", "sebastien bassong", 
                    "kenedy", "jonny evans", "carles gil", "brendan galloway", "deulofeu", "joselu", "clinton n'jie", "jefferson montero", "fernando", 
                    "david silva", "kelechi iheanacho", "andy king", "lucas leiva", "cedric", "gabriel obertan", "adama", "juanmi", "alexandre songl", 
                    "antonio valencia", "victor anichebe", "marcin wasilewski", "pablo zabaleta", "martin demichelis", "gaston ramirez", "pedro obiang",
                    "wes morgan", "miguel angel britos", "angel rangel", "azpilicueta", "john obi mikel", "cuco martina", "youssouf mulumbu", 
                    "steven caulkerl", "sandrol", "leroy ferl", "danny welbeck", "marc muniesa", "giannelli imbula", "kevin stewart", "seydou doumbial", 
                    "jordi amat", "juan manuel iturbe", "peter odemwingie", "alexandre pato", "timothy fosu mensah", "emmanuel emenikel", 
                    "connor randall", "tammy abraham", "brad smith", "cheick tiote", "tokelo rantie", "matthew grimes", "leonardo ulloa" ,"n'golo kante",
                    "yann m'vila", "jordi gomez", "salomon rondon", "claudio yacob", "idrissa gueye", "siem de jong", "carlos sanchez", "ayoze perez", 
                    "oumar niasse", "pape souare", "odion ighalo", "lee chung yong", "gabriel", "alexis sanchez", "hector bellerin", "mohamed elneny",
                    "santi cazorla", "sheyi ojo", "christian benteke", "christian eriksen", "dele alli", "sergio aguero", "nicolas otamendi", "yaya toure",
                    "wilfried bony", "yannick bolasie", "romelu lukaku", "tyias browning", "enner valencia"]

print(len(sb_normalized) - len(fifa_normalized))

for i in range(len(sb_normalized)):
    manual_overrides.update({sb_normalized[i]: fifa_normalized[i]})

print(manual_overrides)

0
{'fernando luiz rosa': 'fernandinho', 'jose leonardo ulloa': 'leonardo ulloa', "n''golo kante": "n'golo kante", "yann gerard m''vila": "yann m'vila", 'jordi gomez garcia penche': 'jordi gomez', 'jose salomon rondon gimenez': 'salomon rondon', 'claudio ariel yacob': 'claudio yacob', 'idrissa gana gueye': 'idrissa gueye', 'siem stefan de jong': 'siem de jong', 'carlos alberto sanchez moreno': 'carlos sanchez', 'ayoze perez gutierrez': 'ayoze perez', 'el hadji baye oumar niasse': 'oumar niasse', "pape n''diaye souare": 'pape souare', 'odion jude ighalo': 'odion ighalo', 'chung yong lee': 'lee chung yong', 'gabriel armando de abreu': 'gabriel', 'alexis alejandro sanchez sanchez': 'alexis sanchez', 'hector bellerin moruno': 'hector bellerin', 'mohamed naser elsayed elneny': 'mohamed elneny', 'santiago cazorla gonzalez': 'santi cazorla', 'oluwaseyi babajide ojo': 'sheyi ojo', 'christian benteke liolo': 'christian benteke', 'christian dannemann eriksen': 'christian eriksen', 'bamidele alli': 'dele alli', 'sergio leonel aguero del castillo': 'sergio aguero', 'nicolas hernan otamendi': 'nicolas otamendi', 'gnegneri yaya toure': 'yaya toure', 'wilfried guemiand bony': 'wilfried bony', 'yannick bolasie yala': 'yannick bolasie', 'romelu lukaku menama': 'romelu lukaku', 'pedro eliezer rodriguez ledesma': 'pedro', 'mario suarez mata': 'mario suarez', 'daniel william john ings': 'danny ings', 'jack frank porteous cork': 'jack cork', 'jose ramiro funes mori': 'ramiro funes mori', 'alexander banor tettey': 'alexander tettey', 'robert brady': 'robbie brady', "dame n''doye": "dame n'doye", "gary o''neil": "gary o'neil", 'daniel andre sturridge': 'daniel sturridge', 'roberto firmino barbosa de oliveira': 'roberto firmino', 'philippe coutinho correia': 'coutinho', 'adam david lallana': 'adam lallana', 'bertrand isidore traore': 'bertrand traore', 'willian borges da silva': 'willian', 'francesc fabregas i soler': 'cesc fabregas', 'kolo habib toure': 'kolo toure', 'nathaniel edwin clyne': 'nathaniel clyne', 'james philip milner': 'james milner', 'jordan brian henderson': 'jordan henderson', 'bojan krkic perez': 'bojan', 'ander herrera aguera': 'ander herrera', 'marouane fellaini bakkioui': 'marouane fellaini', 'juan manuel mata garcia': 'juan mata', 'juan carlos paredes reasco': 'juan carlos paredes', 'diego da silva costa': 'diego costa', 'oscar dos santos emboaba junior': 'oscar', 'mame biram diouf': 'mame diouf', 'guillermo varela olivera': 'guillermo varela', 'angelo obinze ogbonna': 'angelo ogbonna', 'alberto moreno perez': 'alberto moreno', 'divock okoth origi': 'divock origi', "eunan o''kane": "eunan o'kane", 'sebastian coates nion': 'sebastian coates', 'andre ayew pele': 'andre ayew', 'sung yeung ki': 'ki sung yueng', 'gylfi or sigursson': 'gylfi sigursson', 'oriol romeu vidal': 'oriol romeu', 'jonathan howson': 'jonny howson', 'ignacio monreal eraso': 'nacho monreal', 'joel nathaniel campbell samuels': 'joel campbell', 'faustino marcos alberto rojo': 'marcos rojo', 'jesus navas gonzalez': 'jesus navas', 'wayne mark rooney': 'wayne rooney', 'kurt happy zouma': 'kurt zouma', 'cristian gamboa luna': 'cristian gamboa', "john o''shea": "john o'shea", 'mousa sidi yaya dembele': 'moussa dembele', 'jose miguel da rocha fonte': 'jose fonte', 'radamel falcao garcia zarate': 'falcao', 'francis joseph coquelin': 'francis coquelin', 'gabriel imuetinyan agbonlahor': 'gabriel agbonlahor', 'max alain gradel': 'max gradel', 'jose manuel jurado marin': 'jurado', 'chancel mbemba mangulu': 'chancel mbemba', 'dieumerci mbokani bezua': 'dieumerci mbokani', 'sebastien aymar bassong nguena': 'sebastien bassong', 'robert kenedy nunes do nascimento': 'kenedy', 'jonathan grant evans': 'jonny evans', 'carles gil de pareja vicent': 'carles gil', 'brendan joel zibusiso galloway': 'brendan galloway', 'gerard deulofeu lazaro': 'deulofeu', 'jose luis sanmartin mato': 'joselu', "clinton mua n''jie": "clinton n'jie", 'jefferson antonio montero vite': 'jefferson montero', 'fernando francisco reges': 'fernando', 'david josue jimenez silva': 'david silva', 'kelechi promise iheanacho': 'kelechi iheanacho', 'andrew philip king': 'andy king', 'lucas pezzini leiva': 'lucas leiva', 'cedric ricardo alves soares': 'cedric', 'gabriel antoine obertan': 'gabriel obertan', 'adama traore diarra': 'adama', 'juan miguel jimenez lopez': 'juanmi', 'alexandre dimitri song billong': 'alexandre songl', 'luis antonio valencia mosquera': 'antonio valencia', 'victor chinedu anichebe': 'victor anichebe', 'marcin ryszard wasilewski': 'marcin wasilewski', 'pablo javier zabaleta girod': 'pablo zabaleta', 'martin gaston demichelis': 'martin demichelis', 'gaston exequiel ramirez pereyra': 'gaston ramirez', 'pedro mba obiang avomo': 'pedro obiang', 'yann kermorgant': 'wes morgan', 'miguel angel britos cabrera': 'miguel angel britos', 'angel rangel zaragoza': 'angel rangel', 'cesar azpilicueta tanco': 'azpilicueta', 'john michael nchekwube obinna': 'john obi mikel', 'rhu endly martina': 'cuco martina', 'youssouf chafiq mulumbu ngangu': 'youssouf mulumbu', 'steven caulker': 'steven caulkerl', 'sandro ranieri guimaraes cordeiro': 'sandrol', 'leroy fer': 'leroy ferl', 'daniel nii tackie mensah welbeck': 'danny welbeck', 'marc muniesa martinez': 'marc muniesa', 'gilbert gianelli imbula wanga': 'giannelli imbula', 'kevin linford stewart': 'kevin stewart', 'seydou doumbia': 'seydou doumbial', 'jordi amat maas': 'jordi amat', 'juan manuel iturbe arevalo': 'juan manuel iturbe', 'osazemwinde peter odemwingie': 'peter odemwingie', 'alexandre rodrigues da silva': 'alexandre pato', 'timothy evans fosu mensah': 'timothy fosu mensah', 'emmanuel emenike': 'emmanuel emenikel', 'connor steven randall': 'connor randall', 'tammy bakumo abraham': 'tammy abraham', 'bradley shaun smith': 'brad smith', 'cheik ismael tiote': 'cheick tiote', 'tokelo anthony rantie': 'tokelo rantie', 'matt grimes': 'matthew grimes', 'guangtai jiang': 'tyias browning', 'enner remberto valencia lastra': 'enner valencia'}

In [13]:
manual_rows = []

for sb_norm, fifa_norm in manual_overrides.items():

    sb_match = sb_players[sb_players["statsbomb_name_norm"] == sb_norm]
    fifa_match = fifa_players[fifa_players["fifa_name_norm"] == fifa_norm]

    if sb_match.empty:
        print(f"StatsBomb player not found: {sb_norm}")
        continue

    if fifa_match.empty:
        print(f"FIFA player not found: {fifa_norm}")
        continue

    for _, sb_row in sb_match.iterrows():
        fifa_row = fifa_match.iloc[0]

        manual_rows.append({
            "player_id": sb_row["player_id"],
            "player": sb_row["player"],
            "statsbomb_name_norm": sb_row["statsbomb_name_norm"],
            "Player Name": fifa_row["Player Name"],
            "fifa_name_norm": fifa_row["fifa_name_norm"],
            "Shooting": fifa_row["Shooting"],
            "Saving": fifa_row["Saving"],
            "Source": fifa_row["Source"],
            "match_method": "manual",
            "match_score": 100
        })

manual_matches = pd.DataFrame(manual_rows)

In [14]:
exact_mapping = exact_matches[[
    "player_id",
    "player",
    "statsbomb_name_norm",
    "Player Name",
    "fifa_name_norm",
    "Shooting",
    "Saving",
    "Source",
    "match_method",
    "match_score"
]].copy()

player_abilities = pd.concat(
    [exact_mapping, manual_matches],
    ignore_index=True
)

player_abilities = player_abilities.drop_duplicates(
    subset=["player_id"],
    keep="last"
)

player_abilities.head()

,player_id,player,statsbomb_name_norm,Player Name,fifa_name_norm,Shooting,Saving,Source,match_method,match_score
5,3463.0,Junior Stanislas,junior stanislas,Junior Stanislas,junior stanislas,66.166667,8.50,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100
11,3346.0,Joshua King,joshua king,Joshua King,joshua king,76.000000,10.00,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100
18,3814.0,Riyad Mahrez,riyad mahrez,Riyad Mahrez,riyad mahrez,79.666667,10.25,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100
26,10960.0,Jamie Vardy,jamie vardy,Jamie Vardy,jamie vardy,82.333333,13.75,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100
31,3343.0,Dan Gosling,dan gosling,Dan Gosling,dan gosling,66.166667,10.50,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100

CHECKIN UNMATCHED PLAYERS

In [15]:
mapped_ids = set(player_abilities["player_id"])

still_unmatched = sb_players[
    ~sb_players["player_id"].isin(mapped_ids)
]

print("Still unmatched:", len(still_unmatched))
still_unmatched

Still unmatched: 6

      player_id                         player            statsbomb_name_norm
478     28100.0   Ramires Santos do Nascimento   ramires santos do nascimento
547     27853.0            Mauro Matías Zárate            mauro matias zarate
664     15996.0  Éderzito António Macedo Lopes  ederzito antonio macedo lopes
3100     3058.0      Javier Hernández Balcázar      javier hernandez balcazar
3437     5556.0      Miguel Arturo Layún Prado      miguel arturo layun prado
4681     5689.0  Juan Guillermo Cuadrado Bello  juan guillermo cuadrado bello

In [16]:
shots[shots["player_id"].isin(still_unmatched["player_id"])]["player"].value_counts()

player
Mauro Matías Zárate              30
Ramires Santos do Nascimento     10
Éderzito António Macedo Lopes     5
Miguel Arturo Layún Prado         4
Javier Hernández Balcázar         1
Juan Guillermo Cuadrado Bello     1
Name: count, dtype: int64

MERGE INTO SHOTS

In [17]:
shots_with_ability = shots.merge(
    player_abilities[[
        "player_id",
        "Player Name",
        "Shooting",
        "Saving",
        "source",
        "match_method",
        "match_score"
    ]],
    on="player_id",
    how="left"
)

shots_with_ability[[
    "player_id",
    "player",
    "Player Name",
    "Shooting",
    "Saving",
    "match_method"
]].head()

KeyError: "['source'] not in index"

In [ ]:
shots_with_ability["Shooting"].isna().sum()

SAVING RELEVANT DATASETS

In [ ]:
shots_with_ability.to_csv("shots_with_player_ability.csv", index=False)
player_abilities.to_csv("player_abilities_mapping.csv", index=False)

In [ ]:
from sportscraper.fifaindex import run_full_scrape

# Scrape FIFA 19 Premier League (league_id=13) teams, players, and stats
teams_csv, players_csv, stats_csv = run_full_scrape(
    start_year_infix=16,   # FIFA 19
    end_year_infix=16,     # stop at FIFA 19
    league_id=13,          # 13 = Premier League
    outdir="./out",        # output directory for CSVs
    headless=True          # run browser in headless mode
)

: