# MODELING xG TO ACCOUNT FOR PLAYER SCORING ABILITY(INCLUDING THEIR DEXTERITY)

Model C: A + body-part-specific shooter ability

Essentially, this model is to answer the question: "Does context-specific shooter ability provide incremental predictive information beyond conventional shot-context features and generic player ability?"

The SoFIFA dataset was used to acquire the preferred foot and weak foot rating for every player in the shots dataset.

The Preferred Foot will automatically have a rating of 5, and the weak foot will have a rating between 0-5.

## DATA PREPROCESSING

In [1]:
import pandas as pd

shots = pd.read_csv("~/Desktop/Football_Stats/xG/datasets/shots.csv")
shots.head(10)

,location,player,player_id,position,shot_aerial_won,shot_first_time,shot_statsbomb_xg,under_pressure,shot_open_goal,shot_follows_dribble,...,shot_technique_Overhead Kick,shot_technique_Volley,shot_type_Corner,shot_type_Free Kick,shot_type_Open Play,shot_type_Penalty,x,y,distance,angle
0,"[94.5, 42.9]",Aaron Ramsey,3517.0,Right Wing,0,1,0.038832,0,0,0,...,0,0,0,0,1,0,94.5,42.9,25.664372,17.611035
1,"[93.5, 48.4]",Francesc Fàbregas i Soler,3478.0,Right Defensive Midfield,0,0,0.031541,1,0,0,...,0,0,0,0,1,0,93.5,48.4,27.799460,15.648789
2,"[89.8, 22.3]",Alexis Alejandro Sánchez Sánchez,3385.0,Left Wing,0,0,0.006660,1,0,0,...,0,0,0,0,1,0,89.8,22.3,35.004714,11.297814
3,"[98.2, 26.0]",Diego da Silva Costa,5198.0,Center Forward,0,0,0.022902,0,0,0,...,0,0,0,0,1,0,98.2,26.0,25.908300,14.904419
4,"[105.7, 24.2]",Theo Walcott,3668.0,Center Forward,0,0,0.049741,0,0,0,...,0,0,0,0,1,0,105.7,24.2,21.310326,14.633756
5,"[115.1, 45.5]",Pedro Eliezer Rodríguez Ledesma,3958.0,Right Wing,0,0,0.400975,0,0,0,...,0,0,0,0,1,0,115.1,45.5,7.366139,45.695267
6,"[103.9, 23.5]",Aaron Ramsey,3517.0,Right Wing,0,0,0.023207,0,0,0,...,0,0,0,0,1,0,103.9,23.5,23.053416,14.029443
7,"[87.3, 42.5]",Kurt Happy Zouma,3456.0,Right Center Back,0,0,0.020538,0,0,0,...,0,0,0,0,1,0,87.3,42.5,32.795427,13.868931
8,"[92.6, 47.4]",Pedro Eliezer Rodríguez Ledesma,3958.0,Right Wing,0,1,0.033888,0,0,0,...,0,0,0,0,1,0,92.6,47.4,28.381684,15.516625
9,"[95.7, 28.2]",Francesc Fàbregas i Soler,3478.0,Right Defensive Midfield,0,1,0.026702,0,0,0,...,0,0,0,0,1,0,95.7,28.2,27.013515,15.236166

In [2]:
feet = pd.read_csv("~/Desktop/Football_Stats/xG/datasets/preferred_foot.csv")
feet = feet.rename(columns={"Player": "player"})

feet['right_foot_rating'] = None
feet['left_foot_rating'] = None

for i, row in feet.iterrows():
    if row['Preferred Foot'] == "Right":
        feet.at[i, 'right_foot_rating'] = 5
        feet.at[i, 'left_foot_rating'] = row['Weak Foot Rating']
    elif row['Preferred Foot'] == "Left":
        feet.at[i, 'left_foot_rating'] = 5
        feet.at[i, 'right_foot_rating'] = row['Weak Foot Rating']

feet = feet.drop(columns=['Preferred Foot', 'Preferred Foot Rating', 'Weak Foot Rating'])
        
feet.head(10)

                player right_foot_rating left_foot_rating
0     Junior Stanislas                 5                3
1          Joshua King                 5                2
2         Riyad Mahrez                 4                5
3  José Leonardo Ulloa                 5                4
4          Jamie Vardy                 5                3
5          Dan Gosling                 5                3
6           Wes Morgan                 5                3
7           Adam Smith                 5                3
8        N''Golo Kanté                 5                3
9          Robert Huth                 5                3

In [3]:
print(f"{shots.player.nunique() - feet.player.nunique()}")
diff = shots.loc[~shots["player"].isin(feet["player"]), "player"].unique()
print(diff)

4
['Fernando Luiz Roza' "Yann Gérard M'Vila" "Eunan O'Kane" "N'Golo Kanté"]

In [4]:
players = pd.read_csv("~/Desktop/Football_Stats/xG/datasets/player_ratings.csv")
players.head()

,Unnamed: 0,player_id,player,statsbomb_name_norm,Player Name,fifa_name_norm,match_name_norm,Att. Position,Finishing,Shot Power,Long Shots,Volleys,Penalties,Heading,Source,match_method,match_score
0,0,3517.0,Aaron Ramsey,aaron ramsey,Aaron Ramsey,aaron ramsey,aaron ramsey,83.0,75.0,81.0,75.0,79.0,75.0,58.0,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100
1,1,3668.0,Theo Walcott,theo walcott,Theo Walcott,theo walcott,theo walcott,79.0,82.0,75.0,69.0,72.0,74.0,55.0,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100
2,2,5594.0,Branislav Ivanović,branislav ivanovic,Branislav Ivanović,branislav ivanovic,branislav ivanovic,61.0,57.0,73.0,62.0,48.0,58.0,87.0,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100
3,3,3381.0,Nemanja Matić,nemanja matic,Nemanja Matić,nemanja matic,nemanja matic,68.0,64.0,78.0,75.0,74.0,69.0,77.0,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100
4,4,3621.0,Eden Hazard,eden hazard,Eden Hazard,eden hazard,eden hazard,84.0,81.0,79.0,82.0,79.0,86.0,57.0,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100

MERGING BOTH DATASETS

In [5]:
shots_extended= pd.merge(shots, feet, on='player', how='left')
shots_extended= pd.merge(shots_extended, players, on='player', how='left')
shots_extended.head()

,location,player,player_id_x,position,shot_aerial_won,shot_first_time,shot_statsbomb_xg,under_pressure,shot_open_goal,shot_follows_dribble,...,Att. Position,Finishing,Shot Power,Long Shots,Volleys,Penalties,Heading,Source,match_method,match_score
0,"[94.5, 42.9]",Aaron Ramsey,3517.0,Right Wing,0,1,0.038832,0,0,0,...,83.0,75.0,81.0,75.0,79.0,75.0,58.0,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100.0
1,"[93.5, 48.4]",Francesc Fàbregas i Soler,3478.0,Right Defensive Midfield,0,0,0.031541,1,0,0,...,80.0,76.0,77.0,78.0,81.0,80.0,74.0,yarknyorulmaz/fifa-index-player-ratings-datase...,manual,100.0
2,"[89.8, 22.3]",Alexis Alejandro Sánchez Sánchez,3385.0,Left Wing,0,0,0.006660,1,0,0,...,85.0,83.0,82.0,79.0,78.0,77.0,65.0,yarknyorulmaz/fifa-index-player-ratings-datase...,manual,100.0
3,"[98.2, 26.0]",Diego da Silva Costa,5198.0,Center Forward,0,0,0.022902,0,0,0,...,88.0,88.0,83.0,69.0,81.0,76.0,82.0,yarknyorulmaz/fifa-index-player-ratings-datase...,manual,100.0
4,"[105.7, 24.2]",Theo Walcott,3668.0,Center Forward,0,0,0.049741,0,0,0,...,79.0,82.0,75.0,69.0,72.0,74.0,55.0,yarknyorulmaz/fifa-index-player-ratings-datase...,exact,100.0

In [6]:
shots.columns

Index(['location', 'player', 'player_id', 'position', 'shot_aerial_won',
       'shot_first_time', 'shot_statsbomb_xg', 'under_pressure',
       'shot_open_goal', 'shot_follows_dribble', 'goal', 'shot_body_part_Head',
       'shot_body_part_Left Foot', 'shot_body_part_Other',
       'shot_body_part_Right Foot', 'shot_technique_Backheel',
       'shot_technique_Diving Header', 'shot_technique_Half Volley',
       'shot_technique_Lob', 'shot_technique_Normal',
       'shot_technique_Overhead Kick', 'shot_technique_Volley',
       'shot_type_Corner', 'shot_type_Free Kick', 'shot_type_Open Play',
       'shot_type_Penalty', 'x', 'y', 'distance', 'angle'],
      dtype='object')

In [7]:
shots['body_part_rating'] = None
for index, row in shots.iterrows():
    pass

In [8]:
shots_extended.drop(["player_y"], axis=1, inplace=True)
shots_extended.head()

KeyError: "['player_y'] not found in axis"

Normalizing distance angle and shooting values

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
norm_cols = ["distance", "angle", "Shooting"]
shots_extended[norm_cols] = scaler.fit_transform(shots_extended[norm_cols])
shots_extended.head()

In [ ]:
shots_extended.goal.value_counts()

In [ ]:
# import matplotlib.pyplot as plt

# fig, axs = plt.subplots(nrows=3, ncols=3, figsize=(20, 10))
# axs = axs.ravel()

# axs[0].plot(shots_extended['goal'], shots_extended['Shooting'], color='red')
# axs[0].set_title('Shooting vs Goal')

# axs[1].plot(shots_extended['shot_statsbomb_xg'].sort_values(ascending=False), shots_extended['Shooting'], color='red')
# axs[1].set_title('Shooting vs xG')

# axs[2].plot(shots_extended['distance'].sort_values(ascending=False), shots_extended['Shooting'], color='red')
# axs[2].set_title('Shooting vs Distance')

# axs[3].plot(shots_extended['angle'].sort_values(ascending=False), shots_extended['Shooting'], color='red')
# axs[3].set_title('Shooting vs Angle')

# axs[4].plot(shots_extended['shot_type_Penalty'], shots_extended['Shooting'], color='red')
# axs[4].set_title('Shooting vs Penalty')

# axs[5].plot(shots_extended['shot_type_Free Kick'], shots_extended['Shooting'], color='red')
# axs[5].set_title('Shooting vs Free Kick')

# axs[6].plot(shots_extended['shot_type_Open Play'], shots_extended['Shooting'], color='red')
# axs[6].set_title('Shooting vs Open Play')

# plt.tight_layout()

In [ ]:
shots_extended.drop(['location', 'player_x', 'player_id', 'position'], axis=1, inplace=True)
correlations = shots_extended.corrwith(shots_extended['Shooting']).sort_values(ascending=False)

print(correlations)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt


plt.figure(figsize=(10, 6))

sns.barplot(x=correlations.values, y=correlations.index, palette='coolwarm', hue=correlations.index, legend=False)

plt.axvline(x=0, color='black', linestyle='--', linewidth=1)
plt.title(f'Feature Correlations with Shooting', fontsize=14, pad=15)
plt.xlabel('Correlation Coefficient', fontsize=12)
plt.ylabel('Features', fontsize=12)
plt.xlim(-1, 1) 
plt.tight_layout()

plt.show()

# checks out

# angle is not a linear variable 

# more efficeintly work with angle

# get a feature space for every player's preferred foot

# drop shot_open goal or headers to argue that the introduction/loss of an important feature does not yeild significant changes in accuracy

In [ ]:
shots_goals = pd.DataFrame(shots_extended[shots_extended['goal'] == 1])

shots_goals.shape

In [ ]:
shots_extended.to_csv('~/Desktop/Football_Stats/xG/shots_extended.csv', index=False)

In [ ]:
y = shots_extended['goal']
X = shots_extended.drop(['goal', 'shot_statsbomb_xg'], axis=1)

print(f"{X.shape}, {y.shape}")

In [ ]:
X.columns

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
cordinates = X_test[['x', 'y']] # for model visualizations
X_train.drop(["x", "y"], axis=1, inplace=True)
X_test.drop(["x", "y"], axis=1, inplace=True)
X_train.head()

In [ ]:
X_test.head()

## MODELING

### LOGISTIC REGRESSION

In [ ]:
from sklearn.linear_model import LogisticRegression

logistic_regressor = LogisticRegression(max_iter=1000)
logistic_regressor.fit(X_train, y_train)

In [ ]:
y_log= logistic_regressor.predict_proba(X_test)[:,1]
goal_log = logistic_regressor.predict(X_test)
y_log[:10]

In [ ]:
log_df = X_test.copy()
log_df['xG'] = y_log
log_df.iloc[830]

In [ ]:
print(f"goal: {y_test.iloc[100]}, predicted:{goal_log[100]}")

In [ ]:
y_train.value_counts(normalize=True)

## RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(
    n_estimators=500,
    max_depth=8,
    min_samples_split=20,
    min_samples_leaf=10,
    # class_weight='balanced_subsample',
    max_features='sqrt',
    bootstrap=True,
    random_state=42,
    n_jobs=-1
)
# try tuning parameters
random_forest.fit(X_train, y_train)

In [ ]:
y_rf = random_forest.predict_proba(X_test)[:,1]
goal_rf = random_forest.predict(X_test)
y_rf[:10]

In [ ]:
rf_df = pd.DataFrame()
rf_df['Goal'] = y_test.copy()
rf_df['xG'] = y_rf
rf_df.iloc[830]

In [ ]:
print(f"goal: {y_test.iloc[100]}, predicted:{goal_rf[100]}")

## XGBOOST

Run the following code if you don't have xgboost installed in your environment

In [ ]:
# % conda install -c conda-forge xgboost

In [ ]:
import xgboost as xgb

In [ ]:
xgb = xgb.XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    objective='binary:logistic',
    importance_type='gain'
)

xgb.fit(X_train, y_train)

In [ ]:
y_xgb = xgb.predict_proba(X_test)[:,1]
goal_xgb = xgb.predict(X_test)

In [ ]:
xgb_df = pd.DataFrame()
xgb_df['Goal'] = y_test.copy()
xgb_df['xG'] = y_rf
xgb_df.iloc[830]

In [ ]:
print(f"goal: {y_test.iloc[100]}, predicted:{goal_xgb[100]}")

## CATBOOST

Run the following code if you don't have CatBoost installed in your environment

In [ ]:
# %conda install -c conda-forge catboost

In [ ]:
from catboost import CatBoostClassifier, Pool

In [ ]:
catBoost = CatBoostClassifier(
    iterations=100,
    learning_rate=0.1,
    depth=6,
    verbose=10)

train_pool = Pool(X_train, y_train)
eval_pool = Pool(X_test, y_test)
catBoost.fit(train_pool)

In [ ]:
y_cat = catBoost.predict_proba(X_test)[:,1]
goal_cat = catBoost.predict(X_test)

In [ ]:
cat_df = pd.DataFrame()
cat_df['Goal'] = y_test.copy()
cat_df['xG'] = y_cat
cat_df.iloc[830]

In [ ]:
print(f"goal: {y_test.iloc[100]}, predicted:{goal_cat[100]}")

# MODEL EVAULATION

For Logistic Regression

In [ ]:
log_df.sort_values(by='xG', ascending=False).head()

In [ ]:
from sklearn.metrics import log_loss, roc_auc_score, brier_score_loss, accuracy_score, confusion_matrix

print(f"Accuracy: {accuracy_score(y_test, goal_log):.3f}\nLog Loss: {log_loss(y_test, y_log):.3f}\nROC_AUC Score: {roc_auc_score(y_test, y_log):.3f}\nBrier Score: {brier_score_loss(y_test, y_log):.3f}")

For Random Forest

In [ ]:
rf_df.sort_values(by='xG', ascending=False).head()
print(f"Accuracy: {accuracy_score(y_test, goal_rf):.3f}\nLog Loss: {log_loss(y_test, y_rf):.3f}\nROC_AUC Score: {roc_auc_score(y_test, y_rf):.3f}\nBrier Score: {brier_score_loss(y_test, y_rf):.3f}")

For XGBoost

In [ ]:
xgb_df.sort_values(by='xG', ascending=False).head()
print(f"Accuracy: {accuracy_score(y_test, goal_xgb):.3f}\nLog Loss: {log_loss(y_test, y_xgb):.3f}\nROC_AUC Score: {roc_auc_score(y_test, y_xgb):.3f}\nBrier Score: {brier_score_loss(y_test, y_xgb):.3f}")

For CatBoost

In [ ]:
cat_df.sort_values(by='xG', ascending=False).head()
print(f"Accuracy: {accuracy_score(y_test, goal_cat):.3f}\nLog Loss: {log_loss(y_test, y_cat):.3f}\nROC_AUC Score: {roc_auc_score(y_test, y_cat):.3f}\nBrier Score: {brier_score_loss(y_test, y_cat):.3f}")

Confusion Matrices

In [ ]:
goal_dataframes = {"Logistic Regression": goal_log,
                   "Random Forest": goal_rf,
                   "XGBoost": goal_xgb,
                   "CatBoost": goal_cat}

for key, value in goal_dataframes.items():
    cm = confusion_matrix(y_test, value)
    import matplotlib.pyplot as plt
    from sklearn.metrics import ConfusionMatrixDisplay

    # Plotting
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Miss', 'Score'])
    disp.plot(cmap=plt.cm.Blues)
    plt.title(f"{key} Confusion Matrix")
    plt.show()

Calibration Curves

In [ ]:
# %conda install -c conda-forge matplotlib

In [ ]:
from sklearn.calibration import calibration_curve
import matplotlib.pyplot as plt

prob_rf, prob_pred = calibration_curve(
    y_test,
    y_rf,
    n_bins=10
)

plt.plot(prob_pred, prob_rf, marker='o')
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("Predicted Probability")
plt.ylabel("Observed Frequency")
plt.title("Random Forest Calibration")
plt.show()

In [ ]:
prob_rf, prob_pred = calibration_curve(
    y_test,
    y_log,
    n_bins=10
)

plt.plot(prob_pred, prob_rf, marker='o')
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("Predicted Probability")
plt.ylabel("Observed Frequency")
plt.title("Logistic Regression Calibration")
plt.show()

In [ ]:
prob_xgb, prob_pred = calibration_curve(
    y_test,
    y_xgb,
    n_bins=10
)

plt.plot(prob_pred, prob_xgb, marker='o')
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("Predicted Probability")
plt.ylabel("Observed Frequency")
plt.title("XGBoost Calibration")
plt.show()

In [ ]:
prob_cat, prob_pred = calibration_curve(
    y_test,
    y_cat,
    n_bins=10
)

plt.plot(prob_pred, prob_cat, marker='o')
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("Predicted Probability")
plt.ylabel("Observed Frequency")
plt.title("CatBoost Calibration")
plt.show()

## Feature Importance

### For Logistic Regression

Logistic regression uses linear regression. Hence, feature importance can be derived from the rank of the size of the coefficients.

In [ ]:
X_test.columns

In [ ]:
coefficients = logistic_regressor.coef_.flatten()
# coefficients = logistic_regressor.coef_[0]
print(f"Beta coefficients: {coefficients}\n")


bias = logistic_regressor.intercept_[0]
print(f"Bias: {bias}")

importance_df = pd.DataFrame(
    {"Feature": X_test.columns, "Coefficient": coefficients}
)

importance_df["Abs_Coefficient"] = importance_df["Coefficient"].abs()
importance_df = importance_df.sort_values(by="Abs_Coefficient", ascending=True)

plt.figure(figsize=(8, 5))
colors = ["crimson" if c < 0 else "teal" for c in importance_df["Coefficient"]]
plt.barh(importance_df["Feature"], importance_df["Abs_Coefficient"], color=colors)
plt.axvline(x=0, color="black", linestyle="--", linewidth=1)
plt.xlabel("Standardized Coefficient Value (Feature Importance)")
plt.title("Logistic Regression Feature Importance")
plt.tight_layout()
plt.show()

### For Random Forest

The default metric returned when .feature_importances_ is called is the Mean Decrease in Impurity. This is generally the mean reduction in data impurity during the split of a node on the specified feature.

In [ ]:
importance = pd.DataFrame( {"Feature": X_test.columns, "Importance": random_forest.feature_importances_}
).sort_values(by="Importance", ascending=True)

plt.figure(figsize=(8, 5))
plt.barh(importance["Feature"], importance["Importance"], color="teal")
plt.axvline(x=0, color="black", linestyle="--", linewidth=1)
plt.xlabel("Standardized Coefficient Value (Feature Importance)")
plt.title("Random Forest Default Feature Importance")
plt.tight_layout()
plt.show()

Naturally, you'd expect this to favor features with high cardinality. So, the better metric will be to permutate and compute. Here, for every feature, random data points are generated based on the true distribution. This breaks the mathematical relationship between that specific feature and the target variable, while preserving the exact distribution of the data. The forest is run again and the reduction in the evaulation metric of choice(accuracy, roc auc, brier, f1, etc.), is calcluated. This is done multiple times to account for randomness and the results are averaged out.

In [ ]:
from sklearn.inspection import permutation_importance

result = permutation_importance(
    random_forest,
    X_train,         
    y_train,
    n_repeats=50,
    random_state=42,
    scoring="roc_auc"   # accuracy, log loss, or brier score
)

importance = pd.DataFrame( {"Feature": X_test.columns, "Importance": result.importances_mean}).sort_values(by="Importance", ascending=True)

plt.figure(figsize=(8, 5))
plt.barh(importance["Feature"], importance["Importance"], color="teal")
plt.axvline(x=0, color="black", linestyle="--", linewidth=1)
plt.xlabel("Standardized Coefficient Value (Feature Importance)")
plt.title("Random Foreset from Permute and Compute")
plt.tight_layout()
plt.show()

This gives are better importance metric of a feature without the heavy influence of cardinality.

### For XGBoost

The default metric for model importance in XGBoost is the gain. Here, for everynode where the specific feature is used to split the node is considered, and the difference in training loss before or after the split is measured accross all trees. Then divides it by the total number of splits made by that feature to provide an average gain.

**However, consider that xgboost also uses cover to measure a feature's importance by showing how much the feature is responsible for making decisions that affect a vast majority of your training samples. For a single split, the "cover" is calculated using the second-order gradients of the loss function for the samples in that node. For classification, it relates to the confidence of the predictions.**

In [ ]:
importance = pd.DataFrame( {"Feature": X_test.columns, 
                            "Importance": xgb.feature_importances_}).sort_values(by="Importance", ascending=True)

plt.figure(figsize=(8, 5))
plt.barh(importance["Feature"], importance["Importance"], color="teal")
plt.axvline(x=0, color="black", linestyle="--", linewidth=1)
plt.xlabel("Standardized Coefficient Value (Feature Importance)")
plt.title("XGBoost Default Feature Importance")
plt.tight_layout()
plt.show()

Intuitively, most of the datapoints are boolian (Meaning they only take 1s or 0s as inputs). While features like distance, and angle and shooting have high cardinality. I think feature importance techniques that validate based on splits will not offer a consistent basis for all features. 

Hence, I think permute and compute is the best way forward. It does the same thing for each feature: it shuffles the values to match the original distribution, runs the algorithm and averages the evaluation metric of choice against the base line model multiple times and ranks the features afterwards.

CatBoost has two ways of measuring feature importance. Like all decision tree based models, it uses an algortithm that measures the effect of a decision validated on each feature(called "PredictionValuesChange"), which I am going to ignore. Then a second called "LossFunctionChange", also known as "feature dropout", that measures the degradation in the model's loss/metric (e.g., RMSE, Logloss) when a specific feature is removed from the model. A larger drop indicates higher importance.

In [ ]:
importance = catBoost.get_feature_importance(data=train_pool , type="LossFunctionChange")

importance = pd.DataFrame( {"Feature": X_test.columns, 
                            "Importance": importance*10}).sort_values(by="Importance", ascending=True)

plt.figure(figsize=(8, 5))
plt.barh(importance["Feature"], importance["Importance"], color="teal")
plt.axvline(x=0, color="black", linestyle="--", linewidth=1)
plt.xlabel("Standardized Coefficient Value (Feature Importance)")
plt.title("CatBoost Default Feature Importance")
plt.tight_layout()
plt.show()

## PERMUTE AND COMPUTE

In [ ]:
from sklearn.inspection import permutation_importance

models = {"Logistic Regression": logistic_regressor,
          "XGBoost": xgb,
          "Random Forest": random_forest,
          "CatBoost": catBoost}

for name, model in models.items():
    result = permutation_importance(
        model,
        X_train,         
        y_train,
        n_repeats=50,
        random_state=42,
        scoring="roc_auc"   # accuracy, log loss, or brier score
    )

    importance = pd.DataFrame( {"Feature": X_test.columns, 
                                "Importance": result.importances_mean}).sort_values(by="Importance", ascending=True)

    print(importance.tail(10)) # get the top 8 performing features for justification purposes
    # except distanc and angle (see xG_feature_dropout.ipynb)

    plt.figure(figsize=(8, 5))
    plt.barh(importance["Feature"], importance["Importance"], color="teal")
    plt.axvline(x=0, color="black", linestyle="--", linewidth=1)
    plt.xlabel("Standardized Coefficient Value (Feature Importance)")
    plt.title(f"{name} Feature Importance from Permute and Compute")
    plt.tight_layout()
    plt.show()

# MODEL VISUALIZATIONS

In [ ]:
from mplsoccer import Pitch
from matplotlib.colors import LinearSegmentedColormap

pitch = Pitch(
    pitch_type='statsbomb',
    pitch_color='white',
    line_color='black',
    linewidth=1
)
colors = ['red', 'yellow', 'green']
cmap = LinearSegmentedColormap.from_list('my_colormap', colors)
sc = pitch.scatter

In [ ]:
# import numpy as np

# dataframes = {
#     'Logistic Regression': log_df,
#     'Random Forest': rf_df,
#     'XGBoost': xgb_df,
#     'CatBoost': cat_df
# }

# for name, df in dataframes.items():

#     fig, ax = pitch.draw(figsize=(10,8))
#     sc = pitch.scatter(
#         cordinates['x'], cordinates['y'], c=df['xG'],
#         cmap=cmap, edgecolors='black', linewidth=0.5, s=100, ax=ax
#     )

#     cbar = plt.colorbar(sc, ax=ax, orientation='vertical', fraction=0.02, pad=0.02)
#     cbar.set_label(f'{name} xG Probability')

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.gridspec import GridSpec

dataframes = {
    'Logistic Regression': log_df,
    'Random Forest': rf_df,
    'XGBoost': xgb_df,
    'CatBoost': cat_df
}

for name, df in dataframes.items():

    fig = plt.figure(figsize=(18, 14), constrained_layout=True)

    gs = GridSpec(
        2, 1,
        height_ratios=[3, 1],
        figure=fig
    )

    ax_pitch = fig.add_subplot(gs[0])
    ax_hist = fig.add_subplot(gs[1])

    # ---- TOP: Pitch Plot ----
    pitch.draw(ax=ax_pitch)

    sc = pitch.scatter(
        cordinates['x'],
        cordinates['y'],
        c=df['xG'],
        cmap=cmap,
        edgecolors='black',
        linewidth=0.4,
        s=55,
        vmin=0,
        vmax=1,
        ax=ax_pitch
    )

    ax_pitch.set_title(f'{name} xG Shot Map', fontsize=16, pad=10)

    cbar = fig.colorbar(
        sc,
        ax=ax_pitch,
        fraction=0.025,
        pad=0.02
    )
    cbar.set_label(f'{name} xG Probability')

    # ---- BOTTOM: Histogram ----
    ax_hist.hist(
        df['xG'],
        bins=50,
        edgecolor='black'
    )

    ax_hist.set_title(f'{name} xG Distribution', fontsize=14)
    ax_hist.set_xlabel('xG')
    ax_hist.set_ylabel('Frequency')

    plt.show()

# FOUNDATION MODEL APPROACH

TabPFN

In [ ]:
# %conda install -c conda-forge tabpfn 
# %conda install -c conda-forge tabpfn-client
# %pip install tabpfn-client

To use tabpfn:

1. Open https://ux.priorlabs.ai in a browser and log in (or register)
2. Accept the license on the Licenses tab
3. Copy your API Key from https://ux.priorlabs.ai/account
4. Set the environment variable: export TABPFN_TOKEN="<your-api-key>"
 or in Python (before calling .fit()): import os; os.environ["TABPFN_TOKEN"] = "<your-api-key>"

or use mine: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMDA1ZmU3YjUtNjEyZS00MGRjLThiZmYtNjM3ZjYxZWViNDNiIiwiZXhwIjoxODEwNjU4ODk1fQ.QlIbqYxtRGITE3jt1JpCqK2AsM3H2QTll_CdfX_U5jM"

In [ ]:
# import os

# os.environ["TABPFN_TOKEN"] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMDA1ZmU3YjUtNjEyZS00MGRjLThiZmYtNjM3ZjYxZWViNDNiIiwiZXhwIjoxODEwNjU4ODk1fQ.QlIbqYxtRGITE3jt1JpCqK2AsM3H2QTll_CdfX_U5jM"

In [ ]:
from tabpfn_client import TabPFNClassifier, set_access_token

set_access_token("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMDA1ZmU3YjUtNjEyZS00MGRjLThiZmYtNjM3ZjYxZWViNDNiIiwiZXhwIjoxODEwNjU4ODk1fQ.QlIbqYxtRGITE3jt1JpCqK2AsM3H2QTll_CdfX_U5jM")
tabPFN = TabPFNClassifier()
tabPFN.fit(X_train, y_train)
goal_tabPFN = tabPFN.predict(X_test)
y_tabPFN = tabPFN.predict_proba(X_test)[:,1]

In [ ]:
# y_tabPFN = tabPFN.predict_proba(X_test)[:,1]

In [ ]:
print(f"Accuracy: {accuracy_score(y_test, goal_tabPFN):.3f}\nLog Loss: {log_loss(y_test, y_tabPFN):.3f}\nROC_AUC Score: {roc_auc_score(y_test, y_tabPFN):.3f}\nBrier Score: {brier_score_loss(y_test, y_tabPFN):.3f}")